FROM python:3.12-alpine3.19

LABEL key="ml-team"

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY . /app

RUN python3 -m pip install --upgrade pip

RUN pip install -r requirements.txt

CMD ["gunicorn", "--bind", "0.0.0.0:8080", "--config", "deployment/gunicorn_config.py", "app:app"]