steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/sonic-anagram-397306/sentiment_analysis', '-f', 'Dockerfile.prod', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/sonic-anagram-397306/sentiment_analysis']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ml-sentiment'
      - '--image=gcr.io/sonic-anagram-397306/sentiment_analysis'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=1Gi'

images:
  - 'gcr.io/sonic-anagram-397306/sentiment_analysis'